name: Document Conversion md

on:
  push:
    branches:
    - main
    paths:
    - instructions/PL/Zasady.md

jobs:
 convert_test:
   name: Convert PL_md
   runs-on: ubuntu-18.04
   steps:
     - uses: actions/checkout@v1
     - uses: maxheld83/pandoc@v2
       with:
         args: "instructions/PL/Zasady.md -o instructions/PL/Zasady.docx"
     - uses: maxheld83/pandoc@v2
       with:
         args: "instructions/PL/Zasady.docx -o instructions/PL/Zasady.pdf"
     - uses: test-room-7/action-update-file@v1.6.0
       with:
          file-path: |
           instructions/PL/Zasady.docx
           instructions/PL/Zasady.pdf
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
