name: Document Conversion md

on:
  push:
    branches:
    - main
    paths:
    - instructions/PL/Zasady.md

jobs:
 convert_test:
   name: Convert file
   runs-on: ubuntu-18.04
   steps:
     - uses: actions/checkout@v1
     - uses: maxheld83/pandoc@v2
       with:
         args: "instructions/EN/rules.docx -o instructions/EN/rules.md"
     - uses: maxheld83/pandoc@v2
       with:
         args: "instructions/EN/rules.docx -o instructions/EN/rules.pdf"
     - uses: test-room-7/action-update-file@v1.6.0
       with:
          file-path: |
           instructions/EN/rules.md
           instructions/EN/rules.pdf
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
