name: Document Conversion docx

on:
  push:
    branches:
    - main
    - dev
    paths:
    - instructions/EN/rules.docx

jobs:
 convert_test:
   name: Convert EN_docx
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - uses: maxheld83/pandoc@v2
       with:
         args: "instructions/PL/Zasady.docx -o instructions/PL/Zasady.md"
     - uses: maxheld83/pandoc@v2
       with:
         args: "instructions/PL/Zasady.docx -o instructions/PL/Zasady.pdf"
     - uses: test-room-7/action-update-file@v1.6.0
       with:
          file-path: |
           instructions/PL/Zasady.md
           instructions/PL/Zasady.pdf
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
