name: Document Conversion md

on:
  push:
    branches:
    - dev
    paths:
    - instructions/EN/rules.md

jobs:
 convert_test:
   name: Convert EN_md
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - uses: maxheld83/pandoc@v2
       with:
         args: "instructions/EN/rules.md -o instructions/EN/rules.docx"
     - uses: maxheld83/pandoc@v2
       with:
         args: "instructions/EN/rules.md -o instructions/EN/rules.pdf"
     - uses: test-room-7/action-update-file@v1.6.0
       with:
          branch: dev
          file-path: |
           instructions/EN/rules.docx
           instructions/EN/rules.pdf
          commit-msg: Update resources by Actions
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
